"""add cascade to conversation schemas

Revision ID: 0da8f04efc5a
Revises: 3997b5491925
Create Date: 2024-08-24 16:16:33.172409

"""
# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0da8f04efc5a"
down_revision: Union[str, None] = "3997b5491925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration to add cascade to conversation schemas
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_chat_user_id_user"), "chat", type_="foreignkey")
    op.drop_constraint(op.f("fk_file_chat_id_chat"), "file", type_="foreignkey")
    op.drop_constraint(op.f("fk_message_chat_id_chat"), "message", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_reasoning_step_message_id_message"),
        "reasoning_step",
        type_="foreignkey",
    )

    op.create_foreign_key(
        op.f("fk_chat_user_id_user"),
        "chat",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_file_chat_id_chat"),
        "file",
        "chat",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_message_chat_id_chat"),
        "message",
        "chat",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_reasoning_step_message_id_message"),
        "reasoning_step",
        "message",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Migration to remove cascade from conversation schemas
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("email", "user", ["email"], unique=True)
    op.drop_constraint(
        op.f("fk_reasoning_step_message_id_message"),
        "reasoning_step",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("fk_message_chat_id_chat"), "message", type_="foreignkey")
    op.drop_constraint(op.f("fk_file_chat_id_chat"), "file", type_="foreignkey")
    op.drop_constraint(op.f("fk_chat_user_id_user"), "chat", type_="foreignkey")

    op.create_foreign_key(
        op.f("fk_reasoning_step_message_id_message"),
        "reasoning_step",
        "message",
        ["message_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_message_chat_id_chat"), "message", "chat", ["chat_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_file_chat_id_chat"), "file", "chat", ["chat_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_chat_user_id_user"), "chat", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
