"""vector retrieval top k

Revision ID: 1d0c8f667da5
Revises: 40c156115b24
Create Date: 2024-10-01 20:53:26.128328

"""
# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d0c8f667da5"
down_revision: Union[str, None] = "40c156115b24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration to add column vector_top_k to chat table
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column("vector_top_k", sa.Integer(), nullable=False, server_default="3"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Migration to drop column vector_top_k from chat table
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "vector_top_k")
    # ### end Alembic commands ###
