"""add task and feedback schema

Revision ID: 3997b5491925
Revises: a5bd3145a33a
Create Date: 2024-08-25 16:26:13.210630

"""
# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3997b5491925"
down_revision: Union[str, None] = "a5bd3145a33a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration to create the task and feedback tables
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column("task", sa.Column("description", sa.Text(), nullable=False))
    op.add_column("task", sa.Column("initial_system_prompt", sa.Text(), nullable=False))

    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text_feedback", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
            name="fk_feedback_message_id_message",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="fk_feedback_user_id_user",
            ondelete="CASCADE",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Migration to drop the task and feedback tables
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "initial_system_prompt")
    op.drop_column("task", "description")
    op.drop_column("task", "name")

    op.drop_table("feedback")
    # ### end Alembic commands ###
