"""update llm list

Revision ID: 67d81e56ce48
Revises: 1d0c8f667da5
Create Date: 2024-10-13 00:24:12.371402

"""
# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67d81e56ce48"
down_revision: Union[str, None] = "1d0c8f667da5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration to update the llm_model enum to include GEMINI15_PRO and GEMINI15_FLASH
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "llm_model")
    op.add_column(
        "task",
        sa.Column(
            "llm_model",
            sa.Enum(
                "GPT35",
                "GPT4",
                "GPT4O_MINI",
                "GPT4O",
                "GEMINI15_PRO",
                "GEMINI15_FLASH",
                name="llmmodel",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Migration to remove GEMINI15_PRO and GEMINI15_FLASH from the llm_model enum
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "llm_model")
    op.add_column(
        "task",
        sa.Column(
            "llm_model",
            sa.Enum(
                "GPT35", "GPT4", "GPT4O_MINI", "GPT4O", "GEMINI_PRO", name="llmmodel"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
