"""migration message

Revision ID: a59f44cacdb5
Revises: 885d152f4859
Create Date: 2025-02-27 16:18:44.713319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59f44cacdb5'
down_revision: Union[str, None] = '885d152f4859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_chat_user_id_user'), 'chat', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_file_chat_id_chat'), 'file', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('fk_message_chat_id_chat'), 'message', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('fk_reasoning_step_message_id_message'), 'reasoning_step', 'message', ['message_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_user_id_user'), 'task', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_user_id_user'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('fk_reasoning_step_message_id_message'), 'reasoning_step', type_='foreignkey')
    op.drop_constraint(op.f('fk_message_chat_id_chat'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('fk_file_chat_id_chat'), 'file', type_='foreignkey')
    op.drop_constraint(op.f('fk_chat_user_id_user'), 'chat', type_='foreignkey')
    # ### end Alembic commands ###
