"""personalised tasks

Revision ID: f372a6852835
Revises: 0da8f04efc5a
Create Date: 2024-09-14 19:57:42.473851

"""
# pylint: disable=no-member
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f372a6852835"
down_revision: Union[str, None] = "0da8f04efc5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration to add user_id, llm_model, and prompting_technique columns to the task table
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "task",
        sa.Column(
            "llm_model",
            sa.Enum(
                "GPT35", "GPT4", "GPT4O_MINI", "GPT4O", "GEMINI_PRO", name="llmmodel"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "prompting_technique",
            sa.Enum("NONE", "COT", "TOT", "GOT", name="technique"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("fk_task_user_id_user"), "task", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Migration to remove user_id, llm_model, and prompting_technique columns from the task table
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_task_user_id_user"), "task", type_="foreignkey")
    op.drop_column("task", "prompting_technique")
    op.drop_column("task", "llm_model")
    op.drop_column("task", "user_id")
    # ### end Alembic commands ###
